### PR TITLE
edited aspect ratios for more readabilty.

### PR DESCRIPTION
**Pull request by myusf01**
added missing ratios next to resolutions and a "-" 💯

### CODE REVIEW

**Comment by Suzie1** [comment]
Hi, many thanks for this request, I'll check it today and make a decision. Suzie

**Comment by Suzie1** [comment]
Hello, We would like to add the missing aspect ratios on SDXL, but don't think the hyphens are needed. We originally wanted to keep this text compact. We can make a manual update tonight. I'll close if your are okay with that.

thanks again, Suzie

**Comment by myusf01** [comment]
Oh that's okay 👌

**Comment by Suzie1** [comment]
Hi, the change has been deployed, many thanks

**Comment by RockOfFire** [comment]
Thank you for catching this!!  :D

**Pull request closed without merging**
